[font]
size = 14
[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"
[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"
[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"
[font.bold_italic]
family = "Victor Mono"
style = "Bold Italic"
[window]
option_as_alt = "Both"
opacity = 0
[env]
TERM = "xterm-256color"

